# Donwload dependencies
FROM node:12.7-alpine AS build
WORKDIR /usr/src/app
COPY ./ui/package.json ./ui/package-lock.json ./
RUN npm install

# Transpile code
COPY ./ui/src ./src
COPY ./ui/.browserslistrc .
COPY ./ui/angular.json .
COPY ./ui/tsconfig.app.json .
COPY ./ui/tsconfig.base.json .
COPY ./ui/tsconfig.json .
COPY ./ui/tsconfig.spec.json .
RUN ls -al
# Transpile code
RUN npm run build

#copy output to destination
FROM nginx:1.17.1-alpine
COPY ./resources/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/dist/ui /usr/share/nginx/html

EXPOSE 80
