# Build runtime image
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app
COPY ./api ./
WORKDIR /app/ContactsBook.Api
RUN dotnet publish -c Release -o /publish

#copy output to destination
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /publish
COPY --from=build-env /publish .
COPY ./resources/wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

#run app
EXPOSE 80
ENTRYPOINT ["dotnet", "ContactsBook.Api.dll"]
